osx_image: xcode7.1
language: objective-c
xcode_sdk: iphonesimulator9.1
xcode_project: SwiftRandom.xcodeproj
xcode_scheme: SwiftRandom-iOS
notifications:
  email: false
env:
  global:
    - LANG=en_US.UTF-8
before_install:
  - brew update
  - if test -z $(brew outdated | grep -i xctool); then brew upgrade xctool; fi
  - if test -z $(brew list | grep -i carthage); then brew install carthage; fi
install:
  - carthage bootstrap --no-use-binaries --platform ios
